
server:
  port: 8959
spring:
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:

    username: hkoo
    password: hkoo
    url: jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver



  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 494197804420-1ke3o3d15mt52k0n5k54ip8920ciujjp.apps.googleusercontent.com
            client-secret: sdZkIXaOdfTnBiIsP8VUdok8
          github:
            client-id: 751884639d49a11cafdb
            client-secret: 8b21e4cc9bcabb3bdc8991f0a11784295607a998

custom:
  oauth2:
    kakao:
      client-id: 18b1b2deaa6aec3e53d07899549f8587
    naver:
      client-id: HylBNrnld2nVNQPLdZ6V
      client-secret: GgJ8FmAMz5
